name: Release
on:
  workflow_dispatch:
    inputs:
      bump-level:
        type: choice
        required: true
        description: Bump up to [auto / patch / minor / major]
        options:
          - auto
          - patch
          - minor
          - major
        default: auto

concurrency: ${{ github.workflow }}

permissions: {}

jobs:
  call:
    uses: tmknom/release-workflows/.github/workflows/go.yml@214cab0c811e179e4c1448837a13afe83f996ab7 # v0.12.4
    with:
      bump-level: ${{ inputs.bump-level }}
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
